# Basic Tensor operations and GradientTape.

In [1]:
import tensorflow as tf
import numpy as np

2024-07-20 07:15:24.100691: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-20 07:15:24.100825: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-20 07:15:24.260023: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


## Exercise 1 - tf.constant

In [2]:
def tf_constant(array):
    tf_constant_array = tf.constant(array)
    return tf_constant_array

In [3]:
tmp_range = np.arange(1,10)
x = tf_constant(tmp_range)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

## Exercise 2 - tf.square

In [6]:
def tf_square(array):
    array = tf.constant(array)
    tf_squared_array = tf.square(array)
    return tf_squared_array

In [7]:
tmp_range = tf.constant(np.arange(1, 10))
x = tf_square(tmp_range)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

## Exercise 3 - tf.reshape

In [8]:
def tf_reshape(array, shape):
    array = tf.constant(array)
    tf_reshaped_array = tf.reshape(array, shape = shape)
    return tf_reshaped_array

In [10]:
tmp_range = tf.constant(np.arange(1, 10))
x = tf_reshape(tmp_range, shape=(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

## Exercise 4 - tf.cast

In [11]:
def tf_cast(array, dtype):
    array = tf.constant(array)
    tf_cast_array = tf.cast(array, dtype = dtype)
    return tf_cast_array

In [12]:
tmp_array = [1,2,3,4]
x = tf_cast(tmp_array, tf.float32)
x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

## Exercise 5 - tf.multiply

In [13]:
def tf_multiply(tensor1, tensor2):
    tensor1, tensor2 = tf.constant(tensor1), tf.constant(tensor2)
    product = tf.multiply(tensor1, tensor2)
    return product

In [14]:
tmp_1 = tf.constant(np.array([[1,2],[3,4]]))
tmp_2 = tf.constant(np.array(2))
result = tf_multiply(tmp_1, tmp_2)
result

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[2, 4],
       [6, 8]])>

## Exercise 6 - tf.add

In [15]:
def tf_add(tensor1, tensor2):
    tensor1, tensor2 = tf.constant(tensor1), tf.constant(tensor2)
    total = tensor1 + tensor2
    return total

In [16]:
# Check your function
tmp_1 = tf.constant(np.array([1, 2, 3]))
tmp_2 = tf.constant(np.array([4, 5, 6]))
tf_add(tmp_1, tmp_2)

# Expected output:
# <tf.Tensor: shape=(3,), dtype=int64, numpy=array([5, 7, 9])>

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([5, 7, 9])>

## Exercise 7 - Gradient Tape

In [18]:
def tf_gradient_tape(x):
    with tf.GradientTape(persistent = True) as t:
        t.watch(x)
        y = 3 * x**3 - 2*x**2 + x
        z = tf.reduce_sum(y)
    dz_dx = t.gradient(z, x) # 9x^2 − 4^x + 1 (dx/dz) dz/
    # dy/dx is said to be taking the derivative of y with respect to x
    return dz_dx

In [19]:
# Check your function
tmp_x = tf.constant(2.0)
dz_dx = tf_gradient_tape(tmp_x)
result = dz_dx.numpy()
result

# Expected output:
# 29.0

29.0